apiVersion: v1
kind: Pod
metadata:
    name: sample-environment
    labels:
        app: sample-app
spec:
    containers:
        - name: nginx-container
          image: nginx:1.12
          env:
              - name: MAX_CONNECTION
                value: "100"
